### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by hashkash** [lnicco/mvfst-qns#4] opened 2020-09-10 12:00 UTC
Hey Luca,

What's the difference between using the Dockerfile here and the lnicco/mvfst-qns image on docker hub?

I believe the linker fails during the build process when using the Dockerfile, it exists with error code 2. I checked the proxygen build history and the build has been failing for months. How did you get your image to build?

I would like to run a slightly modified version of your image.

Your help is greatly appreciated. Below you can find the output of the build

[100%] Linking CXX executable hq
/usr/bin/ld: CMakeFiles/hq.dir/samples/hq/FizzContext.cpp.o: in function `fizz::HandshakeContextImpl<fizz::Sha384>::getBlankContext() const':
/proxygen/proxygen/_build/deps/include/fizz/protocol/HandshakeContext.h:58: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/fizz/protocol/HandshakeContext.h:58: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: CMakeFiles/hq.dir/samples/hq/FizzContext.cpp.o: in function `fizz::HandshakeContextImpl<fizz::Sha256>::getBlankContext() const':
/proxygen/proxygen/_build/deps/include/fizz/protocol/HandshakeContext.h:58: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/fizz/protocol/HandshakeContext.h:58: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: CMakeFiles/hq.dir/samples/hq/FizzContext.cpp.o: in function `folly::Range<unsigned char const*>::Range<char const*, 0>(folly::Range<char const*> const&)':
/proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha256::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha384::BlankHash'
/usr/bin/ld: /proxygen/proxygen/_build/deps/include/folly/Range.h:311: undefined reference to `fizz::Sha384::BlankHash'
collect2: error: ld returned 1 exit status
make[2]: *** [proxygen/httpserver/CMakeFiles/hq.dir/build.make:254: proxygen/httpserver/hq] Error 1
make[1]: *** [CMakeFiles/Makefile2:1370: proxygen/httpserver/CMakeFiles/hq.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Thanks,

Kash

**Comment by lnicco** [comment] 2020-09-11 06:02
hi @hashkash thanks for reporting. 
the image on dockerhub is built exactly using this Dockerfile. 
The problem is with the compiler version I believe, and the build is indeed failing even in the automation I've set up. 
I'm working on a fix.

**Comment by lnicco** [comment] 2020-09-14 04:09
fixed in https://github.com/facebook/proxygen/commit/36cc983c50037d77a1e77d3c4efd82e19d036f68

you should be able to build the image now. 
Please reopen if there are still issues

**Closed as completed by lnicco** 2020-09-14 04:09 UTC
